/** Auto-generated by scripts/optimize-images.mjs — do not edit by hand */
export const publicImageMeta = {
  "balcony-safety-nets-01": {
    "src": "/images/balcony-safety-nets-01.jpeg",
    "webp": "/images/balcony-safety-nets-01.webp",
    "width": 1014,
    "height": 880
  },
  "balcony-safety-nets-02": {
    "src": "/images/balcony-safety-nets-02.jpeg",
    "webp": "/images/balcony-safety-nets-02.webp",
    "width": 960,
    "height": 1280
  },
  "balcony-safety-nets-03": {
    "src": "/images/balcony-safety-nets-03.jpeg",
    "webp": "/images/balcony-safety-nets-03.webp",
    "width": 1200,
    "height": 1600
  },
  "balcony-safety-nets-04": {
    "src": "/images/balcony-safety-nets-04.jpeg",
    "webp": "/images/balcony-safety-nets-04.webp",
    "width": 1600,
    "height": 1200
  },
  "balcony-safety-nets-05": {
    "src": "/images/balcony-safety-nets-05.jpeg",
    "webp": "/images/balcony-safety-nets-05.webp",
    "width": 1280,
    "height": 720
  },
  "balcony-safety-nets-06": {
    "src": "/images/balcony-safety-nets-06.jpeg",
    "webp": "/images/balcony-safety-nets-06.webp",
    "width": 1200,
    "height": 1600
  },
  "balcony-safety-nets-07": {
    "src": "/images/balcony-safety-nets-07.jpeg",
    "webp": "/images/balcony-safety-nets-07.webp",
    "width": 715,
    "height": 1600
  },
  "clouth-hanger-01": {
    "src": "/images/clouth-hanger-01.jpeg",
    "webp": "/images/clouth-hanger-01.webp",
    "width": 900,
    "height": 1600
  },
  "invisible-grill-01": {
    "src": "/images/invisible-grill-01.jpeg",
    "webp": "/images/invisible-grill-01.webp",
    "width": 1159,
    "height": 1001
  },
  "invisible-grill-02": {
    "src": "/images/invisible-grill-02.jpeg",
    "webp": "/images/invisible-grill-02.webp",
    "width": 1280,
    "height": 1059
  },
  "invisible-grill-03": {
    "src": "/images/invisible-grill-03.jpeg",
    "webp": "/images/invisible-grill-03.webp",
    "width": 1280,
    "height": 1069
  },
  "invisible-grill-04": {
    "src": "/images/invisible-grill-04.jpeg",
    "webp": "/images/invisible-grill-04.webp",
    "width": 1280,
    "height": 1061
  },
  "invisible-grill-05": {
    "src": "/images/invisible-grill-05.jpeg",
    "webp": "/images/invisible-grill-05.webp",
    "width": 1270,
    "height": 1073
  },
  "invisible-grill-06": {
    "src": "/images/invisible-grill-06.jpeg",
    "webp": "/images/invisible-grill-06.webp",
    "width": 1280,
    "height": 1085
  },
  "invisible-grill-07": {
    "src": "/images/invisible-grill-07.jpeg",
    "webp": "/images/invisible-grill-07.webp",
    "width": 1280,
    "height": 1052
  },
  "invisible-grill-08": {
    "src": "/images/invisible-grill-08.jpeg",
    "webp": "/images/invisible-grill-08.webp",
    "width": 1280,
    "height": 1077
  },
  "pigeon-spikes-01": {
    "src": "/images/pigeon-spikes-01.jpeg",
    "webp": "/images/pigeon-spikes-01.webp",
    "width": 472,
    "height": 649
  },
  "pigeon-spikes-02": {
    "src": "/images/pigeon-spikes-02.jpeg",
    "webp": "/images/pigeon-spikes-02.webp",
    "width": 472,
    "height": 649
  },
  "pigeon-spikes-03": {
    "src": "/images/pigeon-spikes-03.jpeg",
    "webp": "/images/pigeon-spikes-03.webp",
    "width": 1500,
    "height": 1500
  }
} as const;
export type PublicImageKey = keyof typeof publicImageMeta;
